CREATE TABLE IF NOT EXISTS luckysheet_report_cell (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  tpl_id BIGINT NOT NULL COMMENT '模板ID',
  sheet_id BIGINT NOT NULL COMMENT 'Sheet ID',
  cell_data TEXT NOT NULL COMMENT 'Luckysheet单元格JSON数据',
  ver INT DEFAULT 1 COMMENT '版本号',
  del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
  tenant_id BIGINT DEFAULT 1 COMMENT '租户ID',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT 'Luckysheet报表单元格数据表';
